#PostgreSQL population deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-dbppgsql
  labels:
    app: dbppgsql
spec:
  selector:
    matchLabels:
      run: dbppgsql
  replicas: 1
  template:
    metadata:
      labels:
        run: dbppgsql
    spec:
      containers:
      - name: dbppgsql
        image: $dbppgsqlImage
        env:
          #Rabbit server credentials
        - name: rabbitServer
          value: $rabbitServer
        - name: rabbitServer_mqadmin
          value: $rabbitServer_mqadmin
        - name: rabbitServer_mqadminpassword
          value: $rabbitServer_mqadminpassword
          #PostgreSQL credentials
        - name: postgreSQL_host
          value: $postgreSQL_host
        - name: postgreSQL_user
          value: $postgreSQL_user
        - name: postgreSQL_password
          value: $postgreSQL_password
        - name: postgreSQL_database
          value: $postgreSQL_database
          #PostgreSQL SSL credentials
        - name: postgreSQL_sslrootcert
          value: "/gcppostgresslserver-ca.pem"
        - name: postgreSQL_sslcert
          value: "/gcppostgresslclient-cert.pem"
        - name: postgreSQL_sslkey
          value: "/gcppostgresslclient-key.pem"