#BigQuery population deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-dbpbigq
  labels:
    app: dbpbigq
spec:
  selector:
    matchLabels:
      run: dbpbigq
  replicas: 2
  template:
    metadata:
      labels:
        run: dbpbigq
    spec:
      containers:
      - name: dbpbigq
        image: $bigqueryImage
        env:
          #Rabbit server credentials
        - name: rabbitServer
          value: $rabbitServer
        - name: rabbitServer_mqadmin
          value: $rabbitServer_mqadmin
        - name: rabbitServer_mqadminpassword
          value: $rabbitServer_mqadminpassword
          #BigQuery credentials
        - name: bigquery_creds
          value: "/bigquerycreds.json"